language: node_js
node_js: stable
before_deploy:
  - yarn build
  - echo 'relaunch.js.org' > styleguide/CNAME
deploy:
  local-dir: styleguide
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  committer-from-gh: true
  on:
    branch: master
